name: weather
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  cupertino_icons: # cupertino icons
  get: # for state management and context less stuff
  logger: # log events in clear way insted of (print)
  flutter_screenutil: # make app responsive
  dio: # for api requests
  http_mock_adapter: # mocking dio for testing
  pretty_dio_logger: # for dio api logging and debugging
  shared_preferences: # shared preferences persistence key value store
  location: # for location
  flutter_launcher_icons: # change app icon
  flutter_svg: # for svg icons
  smooth_page_indicator: # for onboarding screen
  flutter_spinkit: # for loading indicator
  cached_network_image: # for network image
  carousel_slider: # for image slider
  shimmer: # for shimmer effect
  intl: # for date format
  step_progress_indicator: # for progress indicator
  lottie: # for Adobe After Effects animations
  flutter_animate: # for animation
  loading_animation_widget: #for loader

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#6151C3"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/data/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700